{% set name = "ufish" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ufish-{{ version }}.tar.gz
  sha256: 1d1573a0d263739024c5f094a22f842677df1b41543238d60691d182c5cc5810
  patches:
    - setup.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - fire
    - imagecodecs
    - loguru
    - matplotlib-base
    - numpy
    - ome-zarr
    - onnx
    - onnxruntime
    - pandas
    - python >={{ python_min }},<4.0
    - pytorch
    - scikit-image
    - scikit-learn
    - scipy
    - tensorboard
    - torchvision
    - zarr

test:
  imports:
    - ufish
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/ufish
  summary: Deep learning based spot detection for FISH images.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/UFISH-Team/U-FISH

extra:
  recipe-maintainers:
    - goanpeca
    - Nanguage
